{% set version = "2.0" %}

package:
  name: user-agents
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/user-agents/user-agents-{{ version }}.tar.gz
  sha256: 792869b990a244f71efea1cb410ecaba99a270a64c5ac37d365bde5d70d6a2fa

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ua-parser >=0.4.1

test:
  imports:
    - user_agents

about:
  home: https://github.com/selwin/python-user-agents
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A library to identify devices (phones, tablets) and their capabilities by parsing (browser/HTTP) user agent strings'
  dev_url: https://github.com/selwin/python-user-agents

extra:
  recipe-maintainers:
    - pmlandwehr
