travis:
  secure:
    BINSTAR_TOKEN: d9IQUo00BW6TpgMoYZAsZuda198JX+E+6DwKc781U/I19q8xrK4rU/APeKKvjcwctvxb0jxldVgeCV8BIISz5qmiL8wwZcvCy9a3L7Y4f2wRcIPWs7ctrQmoi3BBJaI/+AyDl04DS/On2XKip2WnGfDam62BWKsGyvrRMCz852OTjz6ntvLLOSkuekv1gAGlXbTmfzDsSFwwihcUc0iWddmXcuAL60umMmnoJtCAeJQdE+qSs6YtB+VP81Wa6c/eWJhAHuU1Kz6xTZoqp2uNlpePMQLErkvvOEGrpu0XCY+/pOlmOM80Hvadv7E/X84YcYnZdLunESkTHbOlXuLJeQ4PHYnwVXBtfIVtkaQ5TRU1ITRdvRUTf+4Oe8L0R625U1tVR467NiqR9vtGQ15jWkbq20TIij4FeRez7LCA2dxTO+/0MHg6l9D4cuzxapMJIHHenGPIHwpZm3zqL23TeFtT5ovDvRipENLPRAPrVAOatRENnv/bTD0TRqnlP+IjfRHdMdVVOdC9N8SLMykryWms1KipcohHJqTNuZFQE6wMwds+3OdzMMTzKzP75t32J8mLVJ4+KFNRZjfNlRLNkHDKROu9nBPv0zlykwcXmYv4qRI4lDuJKivCStyIyeGEmGgtFvHMlIcDhzN+YqkFUyFKePPkwA3foQEvVS2DWJ8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
